### ISSUE TITLE
sntp_set_sync_interval

### ISSUE THREAD

**Issue by dragospascale** [tobozo/WiFiManagerTz#1] opened 2022-11-21 13:40 UTC
I cannot find the declaration for sntp_set_sync_interval function so I get error at compiling : "sntp_set_sync_interval' was not declared in this scope"

**Comment by tobozo** [comment] 2022-11-21 14:32
Hi, thanks for your feedback :+1: 

`sntp_set_sync_interval` was added in esp-idf 4.x, so make sure you're using at least 2.x.x version of esp32-arduino, or latest platform-espressif32 in platformio.

It can also be caused by:
- using at an obsolete version of [TimeLib](https://github.com/PaulStoffregen/Time) -> use latest version
- case insensitive conflict with another `time.h` or `Time.h` in the include path -> only occurs on Windows, fixed by removing the other conflicting library)

**Comment by dragospascale** [comment] 2022-11-21 15:03
Thank you . It Works

**Closed** 2022-11-21 17:02 UTC
